### ISSUE TITLE
Robot rotating in place after 10 iterations

### ISSUE THREAD

**Issue by sarath-menon** [dranaju/project#2]
hey, the trained models provided work perfectly. However. the robot is rotating in place after 10 iterations when training from scratch. I believe is the model is saturating quickly.

**Comment by sarath-menon** [comment]
Working perfectly after 250 episodes ~ overnight training

**Comment by trqminh** [comment]
@sarath-menon hope you 're right, my agent are now rotating in place too.

**Comment by trqminh** [comment]
episode 110, my agent is still rotating in place, but I don't despair

**Comment by dranaju** [comment]
It takes a time until the robot learns. But I need to revise this code for you. If you need help, just contact me directly.

**Comment by trqminh** [comment]
@dranaju Thank you for your answer!
the episode is now 300, but the robot is still rotating in place, here is my modification from your project:
- First off, I am launching the turtlebot on gazebo 9 on my computer and running the project in the server by running **python src/ddpg_stage1.py**, the world, that I am using, is similar to turtlebot_stage_2 so I change in the code that **self.stage = 2** instead of **self.stage = rospy.get_param('/stage_number')**
![image](https://user-images.githubusercontent.com/30286786/86691358-f20c1f80-c032-11ea-937b-e14e44668c26.png)
- Secondly, I struggled with installing tf2_py in python3 so I **calculate the yaw** by this:
![image](https://user-images.githubusercontent.com/30286786/86690534-35b25980-c032-11ea-98b8-aa0cc6199847.png)
- Finally, I trained from scratch by getting rid of this "trainer.load_models(4880)"
